services:
  - type: web
    name: mini-war-scanner-api
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    healthCheckPath: /health
    envVars:
      - key: GROQ_API_KEY
        sync: false
      - key: GROQ_MODEL
        sync: false
      - key: DISCORD_WEBHOOK_URL
        sync: false
      - key: ITEMS
        sync: false
      - key: MIN_ALERT_PERCENTAGE
        sync: false
      - key: MAX_ALERT_PERCENTAGE
        sync: false