plugins {
    id 'com.android.application'
}

Properties properties = new Properties()
properties.load(rootProject.file("local.properties").newDataInputStream())

android {
    namespace 'com.miniwar.scanner'
    compileSdk 35

    buildFeatures {
        buildConfig true
    }

    defaultConfig {
        applicationId 'com.miniwar.scanner'
        minSdk 29
        targetSdk 29
        versionCode 1
        versionName '0.1.0'
        buildConfigField "String", "BACKEND_URL", "\"${properties.getProperty('BACKEND_URL', '')}\""
        buildConfigField "String", "SCAN_API_KEY", "\"${properties.getProperty('SCAN_API_KEY', '')}\""
    }
}
